[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
VoronoiCells = "e3e34ffb-84e9-5012-9490-92c94d0c60a4"
